neutrals = FactionInfo():setName("Unabhängige")
neutrals:setGMColor(128, 128, 128)
neutrals:setDescription([[Freie Menschen die sich weder der terranischen Navy noch Mars Tech angeschlossen haben. Darunter zählt alles von Händler, Kreuzschiffen bis zu Schmugglern und Söldnern.]])

tn = FactionInfo():setName("Terranische Navy")
tn:setGMColor(0, 0, 205)
tn:setDescription([[Die terranische Navy entstand als die Menschen begannen ihre Nachbarschaft zu Kolonisieren. Ihre aufgabe besteht für Recht und Ordnung zu sorgen. Zukünftig sollen sie die Konvois in andere Sternensysteme begleiten. Seit erklärung der Unabhängigkeit des Mars befindet sich die Flotte in Alarmbereitschaft und die Produktion von Kriegs und Escort Schiffen wurde beschleunigt.]])
tn:setFriendly(neutrals)

mars = FactionInfo():setName("Mars Tech Union")
mars:setGMColor(205, 0, 0)
mars:setDescription([[Mars Tech Union beschreibt die Fraktion des unabhängig gewordenen Mars. Nach erfolgreicher besiedlung des Planeten entschloßen sich die führenden Köpfe ihre unabhängigkeit zu erklären. Derzeit herrscht ein instabiler Frieden, jederzeit könnte es zu Kampfhandlungen kommen.]])
mars:setFriendly(neutrals)

mars1 = FactionInfo():setName("Mars Tech Union (Krieg)")
mars1:setGMColor(206, 0, 0)
mars1:setDescription([[Kriegszustand.]])
mars1:setEnemy(tn)
mars1:setFriendly(neutrals)

pirat = FactionInfo():setName("Piraten")
pirat:setGMColor(104, 34, 139)
pirat:setDescription([[Diebe und Mördern. Das einzige was sie interessiert ist Profit. Wie sie an diesen kommen ist ihnen egal, das einfachste ist natürlich es anderen Wegzunehmen. Und das wiederum geht einfacher wenn derjenige nicht mehr am Leben ist.]])
pirat:setEnemy(tn)
pirat:setEnemy(neutrals)
pirat:setEnemy(mars)
pirat:setEnemy(mars1)

pirat1 = FactionInfo():setName("Piraten (Alliierte)")
pirat1:setGMColor(103, 33, 138)
pirat1:setDescription([[Diebe und Mördern. Das einzige was sie interessiert ist Profit. Wie sie an diesen kommen ist ihnen egal, das einfachste ist natürlich es anderen Wegzunehmen. Und das wiederum geht einfacher wenn derjenige nicht mehr am Leben ist.]])
pirat1:setFriendly(tn)
pirat1:setFriendly(neutrals)
pirat1:setEnemy(mars)
pirat1:setEnemy(mars1)

al1 = FactionInfo():setName("Alien (Friedlich)")
al1:setGMColor(100, 100, 0)
al1:setDescription([[Unbekannte Spezies.]])

al2 = FactionInfo():setName("Alien (Feindlich)")
al2:setGMColor(0, 100, 100)
al2:setDescription([[Unbekannte Spezies.]])
al2:setEnemy(tn)